cyc_enhance:
  enable_enlarged_vocab: true
  vocab_mode: minimal
  vocab_custom_map: null

ckpt: ./ckpts/Vocab/LDM/B_pair_A3_balance_newest/version_7/checkpoint/epoch299_step350400.ckpt

dataset:
  train:
    class: CPCoreDataset
    pdb_root: CPSea/Model_Generation_and_Evaluation/TestSet/LNR/LNR_complex
    index_path: CPSea/Model_Generation_and_Evaluation/TestSet/LNR/lnr_index.txt
    jsonl_path: CPSea/Model_Generation_and_Evaluation/TestSet/LNR/lnr_meta.jsonl
    rec_chain: R
    lig_chain: L
    pocket_json_dir: epitopes_glad_json_dir
    pocket_json_suffix: _complex_pocket.json
    require_pocket: true
    strict_context: true
    use_covariance_matrix: true
    backbone_only: false
    return_supervision: false
    return_sample_id: true
  test:
    class: CPCoreDataset
    pdb_root: CPSea/Model_Generation_and_Evaluation/TestSet/LNR/LNR_complex
    index_path: CPSea/Model_Generation_and_Evaluation/TestSet/LNR/lnr_index.txt
    jsonl_path: CPSea/Model_Generation_and_Evaluation/TestSet/LNR/lnr_meta.jsonl
    rec_chain: R
    lig_chain: L
    pocket_json_dir: epitopes_glad_json_dir
    pocket_json_suffix: _complex_pocket.json
    require_pocket: true
    strict_context: true
    use_covariance_matrix: true
    backbone_only: false
    return_supervision: false
    return_sample_id: true

dataloader:
  batch_size: 1
  val_batch_size: 1
  shuffle: false
  num_workers: 4

model:
  class: APCycLDMPepDesign
  autoencoder_ckpt: ./ckpts/Vocab/APCyc_AE/version_4/checkpoint/epoch182_step428769.ckpt
  autoencoder_no_randomness: false
  autoencoder_strict_load: true
  hidden_size: 128
  num_steps: 100
  n_layers: 4
  dist_rbf: 16
  dist_rbf_cutoff: 7.0
  n_rbf: 16
  cutoff: 1.0
  max_gen_position: 64
  mode: codesign
  diffusion_opt:
    std: 10.0
  pair_opt:
    pair_dim: 128
    pair_struct_dim: 64
    pair_hidden_dim: 256
    pair_rbf_dim: 32
    pair_rbf_cutoff: 12.0
    edge_type_dim: 16
    pair_anchor_mode: ca
    pair_anchor_channel_idx: 0
    enable_pair_injection: true
    enable_covalent_edges: true
    covalent_edge_type_id: 3
    covalent_edge_start_t: null
    covalent_edge_separate_params: false
    type_hidden: 128
    pair_head_hidden: 128
    min_sep_ss: 3
    allow_ht_alt_pairs: false
    ht_alt_min_end: 1
    mask_mode: teacher
    relax_residue_constraints: true
    lambda_cyc_max: 1.0
    lambda_cyc_schedule: linear
    lambda_b_max: 1.0
    lambda_g_max: 1.0
    struct_proj_dim: 32
    pair_struct_refine: true
    pair_struct_refine_hidden: 64
    pair_cyc_refine: true
    pair_cyc_refine_hidden: 64
    enable_pocket_cross_attn: false
    pocket_cross_attn_dropout: 0.0

sample_opt:
  pbar: true
  strict_ckpt_check: true
  energy_func: default
  energy_lambda: 0.8
  autoencoder_n_iter: 1
  t_hard: 10
  num_samples: 10
  enable_length_override: false
  pep_len: null
  pep_len_min: null
  pep_len_max: null
  auto_min_pep_len: 8
  auto_min_pep_len_threshold: 7
  return_pair_trajectory: false
  use_cg_guidance: true
  property_ckpt: null
  property_ckpts:
    affinity: ./ckpt/property/vocab/property_predictor.affinity_epoch23_val0p592460.pt
    agg_risk: ./ckpt/property/vocab/property_predictor.agg_risk_epoch31_val0p663751.pt
    cycpep_proteolysis_sumscore: ./ckpt/property/vocab/property_predictor.cycpep_proteolysis_sumscore_epoch35_val0p653799.pt
    Pproxy: ./ckpt/property/vocab/property_predictor.Pproxy_epoch30_val0p694006.pt
    Sfinal: ./ckpt/property/vocab/property_predictor.Sfinal_epoch32_val0p410999.pt
    solubility_camsol_score: ./ckpt/property/vocab/property_predictor.solubility_camsol_score_epoch24_val0p606483.pt
    tox_score: ./ckpt/property/vocab/property_predictor.tox_score_epoch39_val0p628541.pt
  guidance_w: null
  guidance_w_map:
    affinity: 8.0
    agg_risk: 0.0
    cycpep_proteolysis_sumscore: 2.0
    Pproxy: 10.0
    Sfinal: 0.0
    solubility_camsol_score: 2.0
    tox_score: 0.0
  guidance_w_min: null
  guidance_w_max: null
  guidance_grad_norm_balance: true
  guidance_grad_norm_eps: 1.0e-6
  guidance_grad_norm_ref: mean
  lambda_max: 0.3
  t_guidance_start: 30
  t_guidance_end: 5

pdb_root: CPSea/Model_Generation_and_Evaluation/TestSet/LNR/LNR_complex
rec_chain: R
lig_chain: L
